### ISSUE TITLE
Developing rationally on the JVM

### ISSUE THREAD

**Issue by steshaw** [qld-jvm/talks#16]

**Comment by mperry** [comment]
@steshaw Can you elaborate on what this means Steve?

**Comment by steshaw** [comment]
It means developing software rationally rather than irrationally.

**Comment by mperry** [comment]
Thanks for your clarification.  It really helped. :(

**Comment by steshaw** [comment]
lol

**Comment by govpack** [comment]
Developing rationally at all is probably an oxymoron ~ where there are at least 7 billion versions of 'rational' - for many in the industry even installing the JVM/some xeno tech/brandX is insane, also i don't think talking about it would help

**Comment by mperry** [comment]
I prefer to develop irrationally so I am guessing you are volunteering to do this talk Steve.  Can we add some detail so others can get excited about the talk?
